window.SITE = {
  system: {
    label: "Structured Field Geometry",
    version: "SFG · 01",
    hints: {
      hover: "Hover · reveal metadata",
      focus: "Select · open reading panel",
    },
  },

  identity: {
    name: "陈帅安",
    nameEn: "ShuaiAn Chen",
    role: "Frontend · Interaction · Generative Systems",
    philosophy: "重复不是惩罚，是雕刻。",
  },

  primary: [
    {
      id: "p-snake",
      type: "project",
      title: "贪吃蛇",
      desc: "Classic snake rebuilt — difficulty tiers, wall modes, audio, mobile + desktop.",
      tags: ["Game", "Canvas"],
      link: "/snake-game/snake/",
      live: true,
      weight: 0.96,
      relevance: 1.0,
    },
    {
      id: "p-companion",
      type: "project",
      title: "Idle Companion",
      desc: "Transparent idle animals as a Chrome extension — quiet presence while you work.",
      tags: ["Extension", "WebM"],
      link: "/snake-game/idle-companion/",
      live: true,
      weight: 0.92,
      relevance: 0.94,
    },
    {
      id: "p-map",
      type: "project",
      title: "扣门地图",
      desc: "WeChat mini program for discovering and sharing climbing crags.",
      tags: ["Mini Program"],
      link: "https://github.com/shuaianchen-glitch/snake-game/tree/main/koumen-map",
      live: true,
      external: true,
      weight: 0.86,
      relevance: 0.88,
    },
    {
      id: "c-webgl",
      type: "capability",
      title: "Canvas / WebGL",
      desc: "Real-time rendering, shader pipelines, and spatial UI prototypes.",
      tags: ["Visual Systems"],
      weight: 0.95,
      relevance: 0.96,
    },
    {
      id: "c-motion",
      type: "capability",
      title: "Motion Systems",
      desc: "Physics-informed motion design with editorial restraint.",
      tags: ["Interaction"],
      weight: 0.9,
      relevance: 0.92,
    },
    {
      id: "c-ux",
      type: "capability",
      title: "Interaction Design",
      desc: "Gestural input, field-based UI, and instrument-like control surfaces.",
      tags: ["Research"],
      weight: 0.86,
      relevance: 0.9,
    },
  ],

  secondary: [
    { id: "n-slow", type: "note", title: "慢即是快", desc: "Velocity without structure is noise.", weight: 0.45, relevance: 0.5 },
    { id: "n-field", type: "note", title: "场先于界面", desc: "Layout follows relational logic, not grids.", weight: 0.5, relevance: 0.55 },
    { id: "n-light", type: "note", title: "光即权重", desc: "Brightness encodes importance.", weight: 0.42, relevance: 0.48 },
    { id: "n-distance", type: "note", title: "距离即关系", desc: "Spatial separation maps conceptual distance.", weight: 0.48, relevance: 0.52 },
    { id: "e-ai", type: "experiment", title: "AI 实验台", desc: "AI and interaction experiments — still recomposing.", tags: ["AI"], live: false, weight: 0.72, relevance: 0.7 },
    { id: "e-tools", type: "experiment", title: "效率工具箱", desc: "Small dev utilities in one quiet toolkit.", tags: ["Tools"], live: false, weight: 0.68, relevance: 0.65 },
    { id: "e-visual", type: "experiment", title: "视觉实验室", desc: "Shader and generative art playground.", tags: ["Visual"], live: false, weight: 0.75, relevance: 0.68 },
    { id: "s-ts", type: "skill", title: "TypeScript", desc: "Typed interfaces for systems that must stay coherent.", tags: ["Build"], weight: 0.62, relevance: 0.72 },
  ],

  soon: {
    message: "In formation — check back soon.",
  },
};
