window.SITE = {
  os: {
    name: "Spatial Information OS",
    version: "SIO · 1.0",
    operator: "ShuaiAn Chen",
  },

  domains: [
    { id: "projects", label: "Projects", focus: "Build Surface" },
    { id: "systems", label: "Systems", focus: "Runtime Layer" },
    { id: "research", label: "Research", focus: "Analysis Field" },
    { id: "notes", label: "Notes", focus: "Signal Archive" },
  ],

  modes: [
    { id: "explore", label: "Exploration", density: 1, secondaryOpacity: 0.55 },
    { id: "build", label: "Build", density: 0.88, secondaryOpacity: 0.28 },
    { id: "analyze", label: "Analyze", density: 0.94, secondaryOpacity: 0.72 },
  ],

  nodes: [
    {
      id: "p-snake",
      category: "project",
      domain: "projects",
      title: "贪吃蛇",
      desc: "Classic snake rebuilt — difficulty tiers, wall modes, audio, mobile + desktop.",
      tags: ["Game", "Canvas"],
      link: "/snake-game/snake/",
      live: true,
      weight: 96,
      relevance: 100,
      depth: 1,
    },
    {
      id: "p-companion",
      category: "project",
      domain: "projects",
      title: "Idle Companion",
      desc: "Chrome extension — transparent idle animals with quiet presence.",
      tags: ["Extension", "WebM"],
      link: "/snake-game/idle-companion/",
      live: true,
      weight: 92,
      relevance: 94,
      depth: 1,
    },
    {
      id: "p-map",
      category: "project",
      domain: "projects",
      title: "扣门地图",
      desc: "WeChat mini program for discovering and sharing climbing crags.",
      tags: ["Mini Program"],
      link: "https://github.com/shuaianchen-glitch/snake-game/tree/main/koumen-map",
      live: true,
      external: true,
      weight: 86,
      relevance: 88,
      depth: 1,
    },
    {
      id: "c-webgl",
      category: "capability",
      domain: "systems",
      title: "Canvas / WebGL",
      desc: "Real-time rendering pipelines and spatial UI prototypes.",
      tags: ["Visual Systems"],
      weight: 95,
      relevance: 96,
      depth: 1,
    },
    {
      id: "c-motion",
      category: "capability",
      domain: "systems",
      title: "Motion Systems",
      desc: "Hardware-grade transitions and focus-driven spatial motion.",
      tags: ["Interaction"],
      weight: 90,
      relevance: 92,
      depth: 1,
    },
    {
      id: "c-spatial",
      category: "capability",
      domain: "systems",
      title: "Spatial UI",
      desc: "Depth-quantized interfaces and material-layer composition.",
      tags: ["Vision Pro"],
      weight: 88,
      relevance: 90,
      depth: 1,
    },
    {
      id: "e-ai",
      category: "experiment",
      domain: "research",
      title: "AI 实验台",
      desc: "AI and interaction experiments — still recomposing.",
      tags: ["AI"],
      live: false,
      weight: 72,
      relevance: 70,
      depth: 2,
    },
    {
      id: "e-visual",
      category: "experiment",
      domain: "research",
      title: "视觉实验室",
      desc: "Shader and generative art playground.",
      tags: ["Visual"],
      live: false,
      weight: 75,
      relevance: 68,
      depth: 2,
    },
    {
      id: "e-tools",
      category: "experiment",
      domain: "research",
      title: "效率工具箱",
      desc: "Small dev utilities in one quiet toolkit.",
      tags: ["Tools"],
      live: false,
      weight: 68,
      relevance: 65,
      depth: 2,
    },
    {
      id: "n-slow",
      category: "note",
      domain: "notes",
      title: "慢即是快",
      desc: "Velocity without structure is noise.",
      weight: 45,
      relevance: 50,
      depth: 2,
    },
    {
      id: "n-field",
      category: "note",
      domain: "notes",
      title: "场先于界面",
      desc: "Layout follows relational logic, not decoration.",
      weight: 50,
      relevance: 55,
      depth: 2,
    },
    {
      id: "n-light",
      category: "note",
      domain: "notes",
      title: "光即权重",
      desc: "Brightness encodes importance in the field.",
      weight: 42,
      relevance: 48,
      depth: 2,
    },
    {
      id: "s-ts",
      category: "skill",
      domain: "systems",
      title: "TypeScript",
      desc: "Typed interfaces for systems that must stay coherent.",
      tags: ["Build"],
      weight: 62,
      relevance: 72,
      depth: 2,
    },
  ],

  soon: { message: "In formation — check back soon." },
};
